services:
  service-server:
    container_name: ctl-server
    restart: always
    user: root
    # image: ctl:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #anonymous volume to prevent the `node_modules` existing in container to be overridden.
    # - /usr/src/app/node_modules
    #   - .:/usr/src/app
    ports:
      - "3000:3000"
    healthcheck:
      test:
        - CMD
        - wget
        - "-q"
        - "--spider"
        - "http://127.0.0.1:3000"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
