backend:
  name: git-gateway
  branch: dev
  publish_mode: editorial_workflow
site_url: "https://dev--coop-tool-library.netlify.app"
media_folder: "src/media"
public_folder: "/media"
collections:
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Information"
        name: "site"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "string"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Physical Address", name: "address", widget: "text"}
          - {label: "Facebook Link", name: "facebook", widget: "string"}
          - {label: "Twitter Username", name: "twitter", widget: "string"}
